{% set version = "1.5.2" %}
{% set name = "linbox" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/linbox-team/linbox/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7b69ab617b15ca6684b29d08531ed8899cd4d07ec75799e5d624c4c0a60dc6b2
  patches:
    # An upstream patch that Sage uses for 8.2: https://github.com/sagemath/sage/blob/8.2.rc4/build/pkgs/linbox/patches/linbox_charpoly_fullCRA.patch
    - patches/9e6e5dd-f4b483c.patch

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - libtool
    - automake
    - pkg-config
    - gmp >=5.0.1,<7
    - mpfr 4.*
    - ntl 10.*
    - libflint
    - givaro
    - iml
    - fflas-ffpack 2.3.*
    - m4ri
    - m4rie
    - openblas 0.2.20|0.2.20.*
  run:
    - gmp >=5.0.1,<7
    - mpfr 4.*
    - ntl 10.*
    - libflint
    - givaro
    - iml
    - fflas-ffpack 2.3.*
    - m4ri
    - m4rie
    - openblas 0.2.20|0.2.20.*

test:
  commands:
    - test -f ${PREFIX}/include/linbox/integer.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib     # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so        # [linux]

about:
  home: http://linalg.org/
  license: LGPLv2.1
  license_file: COPYING.LESSER
  summary: C++ library for exact, high-performance linear algebra
  dev_url: https://github.com/linbox-team/linbox

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
