travis:
  secure:
    BINSTAR_TOKEN: FvLvmv4/fe98dNy9CDSDOYKg53JWLpieavOECnps9qJF3Mxp11dmGCZ1RaruDArMm+/hqMXeUJJHQ1mdmMxV0/ZHQXPBO4JUc7glYGjH8iQdvyTp3hqFYzGxYdX+XpnMl/GXNS4ybjft/najTk8tv7xDYbwpDJTbmY1PJ7eS+rXXVLdGAIsv4arz98D4i8Hsv6ZJ90ci0e5H1qYMRGtOYr0cHda2OfzcWXa2LWAkv7s0rsNsFqrbFXxP0nAKPHwi8nL7iAltkAnPf+VfmiqrQR3P+OkgB1bwPxL2l86mPAejZZoPPS5OK1MuelhEx5phRo85480tGDDTMFeLn2N2CDpTnBUA+hdZrhsFi2S8Q+i/wkPKSXq0Zsuoa5Ql/iDYoCcShOVJAxqdDznqO3tVKFaT+pu9CI2R8YBjbzdlDj4PWkDI/uYfYcZqbkKBK0xom7+Leg0znr3B2Hh0vfHK5h3mw73GUDy7kUPY4pqu4QXBv/eZ6NCQG5RB3dKRGPaJV+dl1dEbQVEcIpmsw1o3OK7Ekr+GTteLSyB8ed5Mmw9rcj51iIXCPV6O4J8qRBhyGra32+ZCARpeczDqBqXoBpAU5neaqRADy/iod3K2s1FS/S/m7CNk5IcQSTgUgOwZU/I5+vAGQvLcNlSgz2DfS6iGyZD3Hlm5LbUrQx70hpU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
